name: Bug Report
description: Submit a bug report.
labels: bug
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is, and why you consider it to be a bug.
    validations:
      required: true
  - type: dropdown
    id: store
    attributes:
      label: Store affected
      description: Which store version of the game did you experience the bug?
      options:
        - Steam
        - EGS
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - MacOS
        - Linux
        - Steam Deck
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which game version did you experience the bug? You can find the current version on the main menu within the game.
    validations:
      required: true
  - type: input
    attributes:
      label: Is it something that used to work before?
      description: If yes, please provide the most recent version where it used to work.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Extra information
      description: Please include any extra information here that will help solve the bug. Include expected behaviour, current behaviour and images or videos if required.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        A list of steps that reproduces the issue.
        1. Step 1
        2. Step 2
    validations:
        required: true